#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

#  Test.
echo "🔍 Running tests before the push..."
pnpm test

echo "✅ Tests passed."

# Biome.
echo "🧼 Formatting with Biome..."
pnpm biome check --write --changed || true

echo "🔍 Running Biome linter..."
pnpm biome check --changed || true

if [ $? -ne 0 ]; then
  echo "❌ Biome found issues that can't be fixed automatically. Push aborted."
  exit 1
fi

echo "✅ Biome checks passed."

# Branch name check.
echo "🔍 Checking branch name..."

branch_name=$(git symbolic-ref --short HEAD)

if ! echo "$branch_name" | grep -Eq '^(feature|fix|hotfix|refactor|docs|test|chore)\/[a-z0-9._-]+$'; then
  echo "❌ Invalid branch name: '$branch_name'"
  echo "The branch name must begin with: feature/ | fix/ | hotfix/ | refactor/ | docs/ | test/ | chore/"
  echo "Example: feature/my-feature, fix/my-bug-fix, hotfix/my-hotfix, refactor/my-refactor, docs/my-docs, test/my-test, chore/my-chore"
  echo "Please rename your branch to follow the naming convention."
  exit 1
fi

echo "✅ Branch name '$branch_name' is valid."