#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Running tests before the push..."
pnpm test

branch_name=$(git symbolic-ref --short HEAD)

if ! echo "$branch_name" | grep -Eq '^(feature|fix|hotfix|refactor|docs|test|chore)\/[a-z0-9._-]+$'; then
  echo "❌ Invalid branch name: '$branch_name'"
  echo "The branch name must begin with: feature/ | fix/ | hotfix/ | refactor/ | docs/ | test/ | chore/"
  exit 1
fi