name: Deploy PR Preview

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed
    
jobs:
  build-preview:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write
      
    steps:
      - name: Download PR Info
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          name: pr-info
          path: ./pr-info
          
      - name: Get PR Number
        id: pr-number
        run: |
          PR_NUMBER=$(cat ./pr-info/pr-number.txt)
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
          echo "PR number is $PR_NUMBER"
          
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Deploy PR Preview
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./dist
          destination_dir: pr-preview/${{ env.PR_NUMBER }}
          
      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const prNumber = process.env.PR_NUMBER;
            const repo = context.repo.repo;
            const owner = context.repo.owner;
            const previewUrl = `https://${owner}.github.io/${repo}/pr-preview/${prNumber}/`;
            
            github.rest.issues.createComment({
              issue_number: parseInt(prNumber),
              owner: owner,
              repo: repo,
              body: `✅ **Tests pasados - Preview disponible**\n\nPuedes ver los cambios de este PR en: [${previewUrl}](${previewUrl})`
            });