name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      checks: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test
        
      - name: Save PR number and branch
        if: success()
        run: |
          mkdir -p ./pr-info
          echo "${{ github.event.pull_request.number }}" > ./pr-info/pr-number.txt
          echo "${{ github.event.pull_request.head.ref }}" > ./pr-info/branch-name.txt
          echo "${{ github.repository }}" > ./pr-info/repository.txt
        
      - name: Upload PR info
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: pr-info
          path: ./pr-info/
          retention-days: 1